site_name: Documentation
site_description: Documentation for miyagi, a node based component development tool for JavaScript templating engines.

docs_dir: docs

extra_css:
  - extra.css

repo_name: mgrsskls/miyagi
repo_url: https://github.com/mgrsskls/miyagi
edit_uri: ""

theme:
  name: material
  font: false
  favicon: img/favicon.svg
  logo: img/logo.svg

plugins:
  - search # necessary for search to work
  - minify:
      minify_html: true

markdown_extensions:
  - codehilite:
      guess_lang: false

nav:
  - Home: index.md
  - Installation: installation.md
  - Configuration:
      - Default configuration: configuration/default-configuration.md
      - Available options: configuration/options.md
      - Via config file: configuration/config-file.md
      - Via CLI: configuration/cli.md
      - Extending a template engine: configuration/extending-a-template-engine.md
  - CLI commands:
      - Starting miyagi: cli-commands/starting-miyagi.md
      - Creating a component: cli-commands/creating-a-component.md
      - Creating mock data: cli-commands/creating-mock-data.md
      - Linting mock data: cli-commands/linting-mock-data.md
      - Creating a build: cli-commands/creating-a-build.md
      - Verbose mode: cli-commands/verbose-mode.md
  - Component files:
      - Introduction: component-files/introduction.md
      - Assets: component-files/assets.md
      - Documentation: component-files/documentation.md
      - Mocks: component-files/mocks.md
      - Schema: component-files/schema.md
      - Template: component-files/template.md
  - The UI: the-ui.md
  - Supported template engines: template-engines.md
  - JavaScript API: javascript-api.md
  - How-to's:
      - Adding JS files: how-to/adding-js-files.md
      - Adding custom CSS and JS per component: how-to/adding-custom-css-and-js-per-component.md
      - Extending a template engine: how-to/extending-a-template-engine.md
      - Using dark and light mode: how-to/using-dark-and-light-mode.md
      - Theming the UI: how-to/theming-the-ui.md
      - Changing the text direction: how-to/changing-the-text-direction.md
      - Changing the HTML language attribute: how-to/changing-the-html-language-attribute.md
      - Configuring the JSON Schema validator: how-to/configuring-the-json-schema-validator.md
      - Organizing components: how-to/organizing-components.md
      - Writing mock data: how-to/writing-mock-data.md
      - Linting mock data: how-to/linting-mock-data.md
      - Changing miyagi's port: how-to/changing-miyagis-port.md
      # - Navigating through the UI: how-to/navigation-through-the-ui.md
      - Adding documentation: how-to/adding-documentation.md
      - Creating a design token overview: how-to/creating-a-design-token-overview.md
      - Navigating through miyagi: how-to/navigating-through-miyagi.md
  - VS Code extension: vs-code-extension.md
